#!/bin/bash

echo "🔥 CONFIGURE XCODE SCHEME RIGHT FUCKING NOW!"
echo "============================================="
echo ""
echo "STEP 1: Open Xcode"
echo "cd ios"
echo "open BetaMe.xcworkspace"
echo ""
echo "STEP 2: Configure Scheme (CRITICAL!)"
echo "1. In Xcode menu: Product → Scheme → Edit Scheme"
echo "2. Click 'Run' in left sidebar"
echo "3. Click 'Options' tab"
echo "4. Find 'StoreKit Configuration' section"
echo "5. CHECK the checkbox to enable it"
echo "6. Select 'BetaCoins.storekit' from dropdown"
echo "7. Click 'Close' to save"
echo ""
echo "STEP 3: Clean and Build"
echo "1. Product → Clean Build Folder (Cmd + Shift + K)"
echo "2. Product → Build (Cmd + B)"
echo ""
echo "STEP 4: Run on Device"
echo "npx expo run:ios --device"
echo ""
echo "🎯 EXPECTED RESULT:"
echo "Apple payment dialog will appear!"
echo "No more 'Purchase Not Available' error!"
echo ""
echo "DO IT NOW! 💪"